add new gnuplot capabilities (surface, scatter3d, wireframe, ...)
JuliaPlots/Plots.jl pull request #3667
Opened 2021-07-25 13:23 UTC by t-bltg

Add new gnuplot capabilities:

```julia
using Plots; gaston()

wframe() = begin
  x = [0, 1, 2, 3]
  y = [0, 1, 2]
  z = [10 10 10 10; 10 5 1 0; 10 10 10 10]
  wireframe(x, y, z, title="3D: Valley of the Gnu from gnuplot manual", legend=:none)
  png("wframe")
end

scatter3() = begin
  x = 0:.1:6π
  scatter3d(x, cos.(x), sin.(x))
  png("scatter3")
end

sombrero() = begin
  x = y = -15:.4:15
  surface(x, y, (x, y) -> @.(sin(sqrt(x * x + y * y)) / sqrt(x * x + y * y)), legend=:none, color=:viridis)
  png("sombrero")
end

wframe()
scatter3()
sombrero()
```

![wframe](https://user-images.githubusercontent.com/13423344/126900625-20032a3f-6025-474c-a284-13ec8cd72f25.png)
![scatter3](https://user-images.githubusercontent.com/13423344/126900627-c9e45938-dcdb-40ae-b87e-3b99cc9bdb00.png)
![sombrero](https://user-images.githubusercontent.com/13423344/126900629-d13ef9a9-8586-44ea-8ade-0810d9711fad.png)

2021-07-25 13:53 UTC, isentropic commented
Do you know how does it work out with grid layout?

2021-07-25 13:56 UTC, t-bltg commented
> Do you know how does it work out with grid layout?

What do you mean ?

2021-07-25 14:04 UTC, isentropic commented
Have you tested if multiplots (layout, multiple subplots, 1 figure), work normal when 3d plots are considered?

2021-07-25 14:17 UTC, t-bltg commented
> Have you tested if multiplots (layout, multiple subplots, 1 figure), work normal when 3d plots are considered?

Fails:
```julia
multiplot3d() = begin
  x = 0:.1:6π
  p1 = scatter3d(x, cos.(x), sin.(x), legend=:none)
  x = y = -15:.4:15
  p2 = surface(x, y, (x, y) -> @.(sin(sqrt(x^2 + y^2)) / sqrt(x^2 + y^2)), legend=:none)
  t = .01:.01:10π
  p3 = plot(t, cos.(t), legend=:none)
  plot((p1, p2, p3)..., layout=@layout([_ _ °; _ ° _; ° _ _]))
  png("multiplot3d")
end
```

, let me see what I can do here.

2021-07-25 15:06 UTC, t-bltg commented
`contour` and `contour3d` are now working !

2021-07-26 04:04 UTC, isentropic requested changes
Overall looks very good to me. Thanks a lot for your contribution. Also, let me know what you think in general about this backend? I personally like gnuplot for what it is (was), are the benefits of gnuplot (terminals, interactiveness, oldschool feel, performance)   well reflected?

2021-07-26 04:04 UTC, isentropic commented on src/backends/gaston.jl
> +gaston_palette(gradient) = begin
Here lets have full function decorators with explicit return

2021-07-26 04:06 UTC, isentropic commented
What could be our selling point for http://docs.juliaplots.org/latest/backends ?
We should also mention that given the age of gnuplot some of the plots functionality can't be achieved at all

2021-07-26 09:02 UTC, t-bltg commented
> What could be our selling point for http://docs.juliaplots.org/latest/backends ?
> We should also mention that given the age of gnuplot some of the plots functionality can't be achieved at all

Let's discuss that https://github.com/JuliaPlots/PlotDocs.jl/pull/250 ?

2021-07-26 09:07 UTC, t-bltg commented
> Overall looks very good to me. Thanks a lot for your contribution. Also, let me know what you think in general about this backend? I personally like gnuplot for what it is (was), are the benefits of gnuplot (terminals, interactiveness, oldschool feel, performance) well reflected?

Well I've used gnuplot a few years ago, mostly because my colleagues were using it for automated tests in CFD codes. It is fast, robust, but most of the users are a bit afraid by the command line. It reaches publication quality, whereas you have to tweak pyplot a lot to reach something acceptable ...

2021-07-28 08:43 UTC, t-bltg commented
@isentropic, are you ok with the latest changes ?

2021-07-28 09:04 UTC, isentropic approved these changes
Looks good to me. Feel free to merge when you feel like it.

2021-07-28 09:04 UTC, merged