Annotation at discrete locations + docs updates
JuliaPlots/Plots.jl pull request #4145
Opened 2022-03-23 00:20 UTC by yha

Support for specifying annotations at discrete values, e.g.
```
using StatsPlots

p = violin(rand(["a","b"],100), rand(100))
annotate!("a", 1/2, "text")
```
![image](https://user-images.githubusercontent.com/4170948/159597572-b73dac97-add2-46a5-a6ad-224bd255cd0e.png)

I also updated docs and example to mention that annotations can be specified as `annotate!(x, y, text)`.

2022-07-09 20:13 UTC, t-bltg requested changes
tests are failing

2022-07-11 20:59 UTC, yha commented
I tried to rebase, but this somehow created a huge merge PR. Also, looks like somehow github comments from other PRs got copied/migrated to this one? Not sure how to restore the original PR now.
(what I did was switch to master, fetch, switch back, `rebase master`, then pulled a single commit, then commit and push)

2022-07-11 21:47 UTC, t-bltg commented
What I would do:
```bash
$ git show b30e3b2de7ce8f83c2789ae76d1e82fb73a1c56c >a_path_outside_the_repo.diff
# cat a_path_outside_the_repo.diff. # check !!
# ... save other commits if needed
$ git reset hard master # or commit
$ git fetch
$ git pull
$ git apply a_path_outside_the_repo.diff
$ git add .
$ git commit -m 'message....'
$ git log -2  # double check everything is ok !
$ git push -f
```

2022-07-12 20:16 UTC, t-bltg commented
Nice, don't forget to run
```julia
using JuliaFormatter
format(["src", "test"])
```
, commit and this should be OK.

2022-07-12 21:44 UTC, t-bltg commented
Example `#59` still needs to be formatted.

2022-07-12 21:52 UTC, yha commented
> Example `#59` still needs to be formatted:

`JuliaFormatter` didn't make that particular change, but I can put it in if that's the preferred style (though it doesn't look like an improvement to my eyes, especially at the function calls).

2022-07-12 21:54 UTC, t-bltg commented
> JuliaFormatter didn't make that particular change

Running https://github.com/JuliaPlots/Plots.jl/pull/4145#issuecomment-1182460899 did create the https://github.com/JuliaPlots/Plots.jl/pull/4145#issuecomment-1182528329 here.

Please apply the diff so that the format check passes.

2022-07-12 21:55 UTC, t-bltg commented
See here: https://docs.juliaplots.org/stable/contributing/#Write-code,-and-format.

2022-07-12 22:10 UTC, t-bltg approved these changes

2022-07-12 23:55 UTC, merged