Do not include plotly.jl twice
JuliaPlots/Plots.jl pull request #4684
Opened 2023-03-07 08:44 UTC by antholzer

At the moment when setting `:plotly` as the default backend (using Preferences) one gets quite a few warning of the type
```
WARNING: Method definition is_subplot_supported(Plots.PlotlyBackend) in module Plots at /home/stephan/.julia/dev/Plots/src/backends/plotly.jl:4 overwritten on the same line (check for duplicate calls to `include`).
  ** incremental compilation may be fatally broken for this module **
```
They are the result of `src/backend/plotly.jl` being included twice. The following commit is a workaround that seems to fix this.

2023-03-07 10:42 UTC, t-bltg commented
No: if this is backend specific, then it should be fixed in `src/backends.jl`, somewhere along

https://github.com/JuliaPlots/Plots.jl/blob/20726c880f06cfcee1428205f72d70d07e7e53b5/src/backends.jl#L537-L538

2023-03-08 15:13 UTC, t-bltg commented
`is_subplot_supported` and `is_string_supported` seem to have been removed in https://github.com/JuliaPlots/Plots.jl/commit/03a9fc341920634b00531b06a21761442c59faf8, can you remove them in this PR ?

We could also use `Plot.PLOTS_DEFAULT_BACKEND == "plotly" || ...` as an alternative (since it is loaded from `Preferences`), I'm wondering if this is more robust than using `CURRENT_BACKEND.sym` ...

2023-03-08 17:01 UTC, t-bltg requested changes
Let's use `PLOTS_DEFAULT_BACKEND` instead since the issue is related to `Preferences` in the first place.

2023-03-08 17:01 UTC, t-bltg commented on src/backends.jl
> +    CURRENT_BACKEND.sym === :plotly || include(_path(:plotly))
```suggestion
    PLOTS_DEFAULT_BACKEND == "plotly" || include(_path(:plotly))
```

2023-03-08 17:01 UTC, t-bltg commented on src/backends.jl
> +        end
```suggestion
        PLOTS_DEFAULT_BACKEND == "plotly" || @eval include(_path(:plotly))
```

2023-03-09 04:38 UTC, t-bltg commented
I'm also curious to know if only removing the function definition lines actually suffice to solve your issue.

2023-03-09 08:07 UTC, antholzer commented
Sorry I did not include the full output of the warnings. All function definitions have one not just the ones I removed above.

Here is the output when I remove these two functions (actually only one since the other one was commented) but do not include the fix: https://gist.github.com/antholzer/64b71a4ea7ac32461b603f4e7de3fdc6)

2023-03-09 08:53 UTC, t-bltg approved these changes

2023-03-09 09:01 UTC, merged